def fun_error():
    print('123')

